language: node_js
node_js:
  - "9.5.0"
cache: yarn
install:
  - npm i -g yarn && yarn
before_script:
  - yarn prod
deploy:
  provider: gcs
  bucket: "www.idea-zine.com"
  skip_cleanup: true
  acl: public-read
  local-dir: dist
