language: node_js
node_js:
  - "9.5.0"
cache: yarn
dist: trusty
sudo: false
install:
  - npm i -g yarn && yarn
deploy:
  provider: gcs
  bucket: "www.idea-zine.com"
  skip_cleanup: true
  acl: public-read
  local-dir: dist

